apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      containers:
      - name: nfs-client-provisioner
        image: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
        volumeMounts:
        - name: nfs-client-root
          mountPath: /persistentvolumes
        env:
        - name: PROVISIONER_NAME
          value: storage.k8s.io/nfs
        - name: NFS_SERVER
          value: 10.0.0.50  # IP of your NFS server
        - name: NFS_PATH
          value: /srv/nfs/kubedata
      volumes:
      - name: nfs-client-root
        nfs:
          server: 10.0.0.50
          path: /srv/nfs/kubedata
